seed: 21

data:
  train_data: data/train.csv
  val_data: data/val.csv
  cat_features_indices: [0]

model:
  n_estimators: 100
  learning_rate: 0.1
  max_depth: 1

experiments:
  dir: "experiments"
  save_to: "latest"